defaults:
  - model: actmix
  - dataset: power_plant
  - training: default
  - _self_

seed: 1192
experiment_name: ${model.name}_${dataset.name}

paths:
  root_dir: .
  experiment_dir: ${paths.root_dir}/experiments/${experiment_name}
  log_dir: ${paths.experiment_dir}/logs
  checkpoint_dir: ${paths.experiment_dir}/checkpoints

hydra:
  run:
    dir: ${paths.log_dir}
  sweep:
    dir: ${paths.log_dir}/sweeps
    subdir: ${hydra.job.num}
